### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by bestcondition** [yozorayuki/dst_mod_fast_travel#1]
[05:18:58]: [string "scripts/entityscript.lua"]:1107: assertion failed!
LUA ERROR stack traceback:
=[C]:-1 in (global) assert (C) <-1--1>
scripts/entityscript.lua:1107 in (method) GetDistanceSqToInst (Lua) <1106-1111>
   self (valid:false) =
      DynamicShadow = DynamicShadow (0x2aae0430)
      inlimbo = false
      GetMoistureRateScale = function - scripts/prefabs/player_common.lua:146
      SetCameraDistance = function - scripts/prefabs/player_common.lua:1018
      ScreenFlash = function - scripts/prefabs/player_common.lua:1080
      playercolour = table: 0x184a0410
      IsOverheating = function - scripts/prefabs/player_common.lua:116
      Light = Light (0x1e2eb850)
      _OnDespawn = function - scripts/prefabs/wendy.lua:38
      _isrezattuned = false
      OnRemoveEntity = function - scripts/prefabs/player_common.lua:664
      ShowHUD = function - scripts/prefabs/player_common.lua:1000
      ShowGiftItemPopUp = function - scripts/prefabs/player_common.lua:1012
      sg = sg="wilson", state="idle", time=4.93, tags = "idle,canrotate,"
      IsHUDVisible = function - scripts/prefabs/player_common.lua:990
      ApplyScale = function - scripts/prefabs/player_common.lua:1095
      SetGhostMode = function - scripts/prefabs/player_common.lua:577
      ShowActions = function - scripts/prefabs/player_common.lua:994
      OnWakeUp = function - scripts/prefabs/player_common.lua:865
      Transform = Transform (0x2bceb3f0)
      actionreplica = table: 0x2b7fd6f0
      actioncomponents = table: 0x295d58b0
      lower_components_shadow = table: 0x29d6d840
      GetMaxMoisture = function - scripts/prefabs/player_common.lua:136
      CanUseTouchStone = function - scripts/prefabs/player_common.lua:86
      dycshb_cstyle_net = net_string (0x1fdd4f40)
      ShakeCamera = function - scripts/prefabs/player_common.lua:1038
      OnDespawn = function - scripts/prefabs/player_common.lua:887
      persists = false
      MiniMapEntity = MiniMapEntity (0x2d458690)
      IsFreezing = function - scripts/prefabs/player_common.lua:106
      _OnLoad = function - scripts/prefabs/wendy.lua:55
      replica = table: 0x295d5910
      GetTemperature = function - scripts/prefabs/player_common.lua:96
      GUID = 323508
      ghostenabled = true
      EnableMovementPrediction = function - scripts/prefabs/player_common.lua:521
      abigail_flowers = table: 0x1956b5d0
      SetCameraZoomed = function - scripts/prefabs/player_common.lua:1024
      Network = Network (0x26e01230)
      GetMoisture = function - scripts/prefabs/player_common.lua:126
      OnPreLoad = function - scripts/prefabs/player_common.lua:745
      LightWatcher = LightWatcher (0x2a705c00)
      has_AlwaysOnStatus = true
      inherentactions = table: 0x150eda20
      spawntime = 17608.767585035
      SnapCamera = function - scripts/prefabs/player_common.lua:1030
      _OnSave = function - scripts/prefabs/wendy.lua:49
      migration = table: 0x2a0acab0
      Physics = Physics (0x285d7dd0)
      should_Estimate_Stale = true
      ScreenFade = function - scripts/prefabs/player_common.lua:1071
      SaveForReroll = function - scripts/prefabs/player_common.lua:1128
      name = 2834535446
      prefab = wendy
      LoadForReroll = function - scripts/prefabs/player_common.lua:1140
      entity = Entity (0x19fea140)
      children = table: 0x2c95e6e0
      IsCarefulWalking = function - scripts/prefabs/player_common.lua:160
      AttachClassified = function - scripts/prefabs/player_common.lua:653
      OnSleepIn = function - scripts/prefabs/player_common.lua:837
      IsActionsVisible = function - scripts/prefabs/player_common.lua:984
      OnLoad = function - scripts/prefabs/player_common.lua:755
      OnSave = function - scripts/prefabs/player_common.lua:714
      SoundEmitter = SoundEmitter (0x2d4585d0)
      ShowWardrobePopUp = function - scripts/prefabs/player_common.lua:1006
      userid = KU_0j0lUlXd
      GetSandstormLevel = function - scripts/prefabs/player_common.lua:156
      AnimState = AnimState (0x2a4f5c40)
      _winters_feast_music = table: 0x27aa7e60
      DetachClassified = f
[05:18:58]: [string "scripts/entityscript.lua"]:1107: assertion failed!
LUA ERROR stack traceback:
    =[C]:-1 in (global) assert (C) <-1--1>
    scripts/entityscript.lua:1107 in (method) GetDistanceSqToInst (Lua) <1106-1111>
    scripts/entityscript.lua:1114 in (method) IsNear (Lua) <1113-1115>
    ../mods/workshop-1530801499/scripts/components/travelable.lua:247 in (field) fn (Lua) <234-319>
    scripts/scheduler.lua:177 in (method) OnTick (Lua) <155-207>
    scripts/scheduler.lua:371 in (global) RunScheduler (Lua) <369-377>
    scripts/update.lua:180 in () ? (Lua) <159-238>
	
[05:18:59]: Warning: Widget:SetFocusFromChild is happening on a widget outside of the screen/widget hierachy. This will cause focus moves to fail. Is 	ScriptErrorWidget	not a screen?	
[05:18:59]: stack traceback:
	scripts/widgets/widget.lua:605 in (method) SetFocusFromChild (Lua) <602-627>
	scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
	scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
	scripts/widgets/widget.lua:656 in (method) SetFocus (Lua) <629-665>
	scripts/widgets/menu.lua:83 in (method) SetFocus (Lua) <74-85>
	scripts/widgets/scripterrorwidget.lua:109 in (method) OnUpdate (Lua) <102-119>
	scripts/update.lua:90 in () ? (Lua) <33-129>

**Comment by yozorayuki** [comment]
初步推测问题原因为：传送倒数结束时，进行传送的玩家退出游戏（or离开当前世界）。
不知道你提出的问题是否可复现。
我会进一步进行测试。

**Comment by yozorayuki** [comment]
我已经复现了你所反馈的问题，证实了我上面的推断。这是由原MOD带来的问题，我已经进行了修复。稍后请进行更新，感谢你的反馈。
